### ISSUE TITLE
JacksonJsonDecoder provides only raw class information to the ObjectMapper

### ISSUE THREAD

**Issue by rstoyanchev** [spring-projects/spring-reactive#112]
Currently it does:
````Java
ObjectReader reader = this.mapper.readerFor(elementType.getRawClass());
````

**Comment by rstoyanchev** [comment]
Note the existing MappingJackson2HttpMessageConverter (and the GenericHttpMessageConverter respectively) allow passing in a contextClass.

**Comment by sdeleuze** [comment]
Fixed by https://github.com/spring-projects/spring-reactive/commit/098a4474feefd3229261737c8e872619f776b8cd. I have created a dedicated issue for the [contextClass support](https://github.com/spring-projects/spring-reactive/issues/117) since I would like to think about it with also JsonView support in mind (in order to clarify how we pass additional informations to codecs).
