### ISSUE TITLE
Remove dependency on Servlet API in spring-web exception hierarchy

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects/spring-reactive#45]
`ResponseBodyResultHandler` throws `HttpMediaTypeNotAcceptableException`, but sadly this exception inherits from `ServletException`, resulting in a mandatory dependency on Servlet API.

We should avoid that, by maybe using a `MediaType`exception that does not inherit from `ServletException`.

**Comment by sdeleuze** [comment]
cc @poutsma @rstoyanchev

**Comment by rstoyanchev** [comment]
Good point. There are a number of others too. We might have to take it on a case-by-case basis. 

HttpMediaTypeNotAcceptableException extends HttpMediaTypeException both in the web package. I can see having a MimeTypeException as a parent class that naturally doesn't collide with the existing class. The sub-class could be HttpNotAcceptableMimeTypeException. Just a thought for now.

**Comment by bclozel** [comment]
I don't get the actual motivations behind this issue. Are we facing 1) or 2)?

1. We don't want those exceptions to inherit from `ServletException` because, just like the request/response hierarchy, we want to integrate smoothly with Spring web. But we don't want to change the inheritance hierarchy for compatibility reasons.
2. We think that those exceptions are different concepts and deserve a separate hierarchy.

With case 2), I don't get what the difference is.
For case 1), the only problem I see is binary compatibility. With Spring 5, this is probably our only opportunity for this, since we're moving to JDK8 as a baseline and we want to embrace both web models (Spring MVC and web reactive) as first class citizens.

**Comment by sdeleuze** [comment]
I would say 1), and I agree that Spring 5 could be an opportunity to modify `HttpMediaTypeException` (and maybe a few others ones) to not extend `ServletException` anymore since `HttpMediaTypeException` and `HttpMediaTypeNotAcceptableException` are exactly what we need here, and creating a parallel Exception hierarchy would be confusing.

The good news is that even if `HttpMediaTypeException` does not extend `ServletException` anymore, I believe it will be automatically wrapped into a `NestedServletException` (thanks to [these lines in FrameworkServlet.java](https://github.com/spring-projects/spring-framework/blob/master/spring-webmvc/src/main/java/org/springframework/web/servlet/FrameworkServlet.java#L980-L983)) so even if we cannot say that this change will have 0 side effect, I would argue that the fact the Servlet container will still receive a `ServletException` making that change impact quite low, and reasonable from my point of view to do in a major release as proposed by @bclozel.

Given the new goal of `spring-web` that should try to avoid requiring Servlet API when this is not absolutely needed, and given the benefit it will have (allow us to use these exception for non Servlet based code without creating an unneeded parallel exception hierarchy), that may be a good fit for Spring 5.

Any thoughts?

**Comment by jhoeller** [comment]
From a wider dependency arrangement, it might make sense to have new variants of those exceptions somewhere within `org.springframework.http`, possibly deprecating the ones in `web` (or using them as wrappers for the `http` ones, only rethrown that way in a Servlet environment)...

**Comment by rstoyanchev** [comment]
We now have the RequestMappingHandlerMapping + base classes which has the same issue.

**Comment by rstoyanchev** [comment]
I've created a starting point for a new exception hierarchy under `org.springframework.web.server` which is a new package in spring-reactive but will be in spring-web.

There is the top-level [ResponseStatusException](https://github.com/spring-projects/spring-reactive/blob/master/src/main/java/org/springframework/web/server/ResponseStatusException.java) and then sub-classes for concrete response status codes. This is the commit with new exceptions https://github.com/spring-projects/spring-reactive/commit/660c754bd8fe3ec566a3f193305c8d7d08dd467a and also the commit that replaces the existing exceptions https://github.com/spring-projects/spring-reactive/commit/889e56530baacdfbfa53393244f0f1e2fa66e10b.

The general idea is that the hierarchy is organized around response status codes where each exception may cover a variety of situations. This is already the case for 405, 416 which may be due to parse errors vs no match. I believe the same approach can work for other status codes even something as broad as 400. Hence reducing the overall number of exceptions and introducing new ones only when truly needed.

As for the existing exceptions and their use in spring-webmvc we can consider deprecating them as suggested earlier and for the time have them extend the new exceptions.

**Comment by rstoyanchev** [comment]
Follow-up after discussion with @poutsma. 

Most of the new exceptions are generally applicable for HTTP server-side processing (both by Spring and by applications) including ResponseStatusException, MethotNotAllowedStatusException, NotAcceptableStatusException, and UnsupportedMediaTypeStatusException where the sub-classes support 405, 406, and 415 with additional information to be added as response headers. 

By contrast `BadRequestStatusException` carries an optional `MethodParameter` field (and will have others like `BindingResult`) and has been renamed to `ServerWebInputException` in https://github.com/spring-projects/spring-reactive/commit/f12d25488c6012b630ae9b4d88c58d2d2225386c to make it clear it is more framework-specific vs `ResponseStatusException(400)`.

The generic HTTP exceptions could be in the `http.server` package but they're needed in the web framework (i.e. `spring-web-reactive`) and could also live in the `web.server` package under `spring-web` which allows them to be shared with `spring-webmvc`. Another consideration is that currently client-side HTTP exceptions are also in the `web.client` package rather than in `http.client`.
