### ISSUE TITLE
Consistent HTTP error handling for exceptions emitted in handler method

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects/spring-reactive#47]
My experiments with [spring-reactive-playground](https://github.com/sdeleuze/spring-reactive-playground) have shown that when an error occurs on user side (in my tests I shutdown the PG database, and I send a `GET http://localhost:8080/postgres` with `Accept: application/json` header), the behavior observed with the HTTP response is not consistent.

The result observed are:
 - Reactor: response received with status code 200
 - RxNetty response received with status code 0
 - Tomcat: response received with status code 500 after 30 seconds
 - Jetty: response received with status code 500 after 30 seconds
 - Undertow : no response

These difference may come from the various HTTP server engines or from our integration with them. Maybe the status code + headers is written too early (before the error is received).

In all cases, this is a very interesting topic, and I think we should be able to define, regardless of the HTTP engine used:
 - When the status code is written
 - How we could make sure that when the error come before the first element emitted, a 500 status code is written
 - What happen when an error occur after the status code + headers have been written (maybe there is a way to close the response in a way when the client understand that something wrong occurred).

**Comment by rstoyanchev** [comment]
Heh, good to know and not surprising. Exception handling is up next.

**Comment by rstoyanchev** [comment]
Some further insight into the scope of this issue.

After a call to `ServerHttpResponse#setBody(Publisher)` the response is committed. This makes sense intuitively except when you consider that the `Publisher` may fail before ever producing any data, i.e. entirely an application/business exception that occurs before anything is written to the response, yet with no way to render an error response.

The following is sufficient to demonstrate the issue:
````java
@RequestMapping("/boo")
@ResponseBody
public Publisher<String> handle() {
	return Publishers.error(new IllegalStateException("Boo"));
}
````
The 200 on RxNetty is because the response is committed as soon as `write` is called. The 500 with the Servlet containers is because our Servlet bridge currently doesn't do anything with errors from the Publisher and the request hangs and simply times out after 30 seconds.

The first step is to change our own `ServerHttpResponse` implementations to keeps headers in sync with the underlying runtime along these lines (see [for example](https://github.com/rstoyanchev/spring-reactive/commit/4f77c0b456a1316e690a4ab328efcec98e9fdd05)).

The problem however goes deeper. RxNetty and also Reactor Net currently simply do not allow more than one call to write to the response, which again makes sense in general, but basically assumes the given Publisher or Observable will not fail. Effectively that means we cannot call `write` until we know it will write at least one item.

**Comment by rstoyanchev** [comment]
https://github.com/ReactiveX/RxNetty/issues/458

**Comment by rstoyanchev** [comment]
This is resolved through the use of our own custom WriteOperator.
