### ISSUE TITLE
@RestController requires @ResponseBody

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-reactive#62]
I copied some code from `RequestMappingHandlerMappingTests` to try and set up a "Hello World" app. This works

```
@RestController
public class Controller {
	@RequestMapping("/")
	@ResponseBody
	public String handle() {
		return "Hello World";
	}
}
```

and this doesn't:

```
@RestController
public class Controller {
	@RequestMapping("/")
	public String handle() {
		return "Hello World";
	}
}
```

So I guess it's just a missing feature (the semantics of `@RestConrtoller` is not quite preserved from Spring MVC).

BTW the one that fails does so in a strange way, silently and never returning an HTTP response, so the client blocks forever with no feedback.

**Comment by rstoyanchev** [comment]
There was a NPE in `SimpleHandlerResultHandler` and the error signal was allowed to escape to the runtime and from there it depends on the runtime. RxNetty hangs and so does Reactor IO it seems. I'm guessing you're only adding a `DispatcherHandler` without exception handling, which would ensure a 500 error:
````java
WebToHttpHandlerBuilder.webHandler(dispatcherHandler)
    .exceptionHandlers(new ExceptionHandlingWebHandler)
    .build();
````

That said I've made changes to make sure unresolved exceptions are logged and turned into a 500 even at the lowest level, i.e. `WebToHttpHandlerAdapter`. I've also fixed the NPE so it becomes an ISE for no matching result handler. And since it was trivial to do so I also added support for @RestController.

As a general comment yes you may find some surprising gaps. What we have at the moment is more aimed at breadth than depth.

**Comment by rstoyanchev** [comment]
Forgot to reference commits https://github.com/spring-projects/spring-reactive/commit/623c996494e809833a7b6473be981bd1d78327dc and https://github.com/spring-projects/spring-reactive/commit/74d9246a7b04995faff45ac18628b9d874e22437.
