### ISSUE TITLE
ClientHttpRequestFactory.createRequest does not fully create request

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-reactive#82]
Give the method name, it is not intuitive to me that `ClientHttpRequestFactory.createRequest` creates a request but does not populate every attribute on the request. `DefaultRequestBuilder` is [setting the body](https://github.com/spring-projects/spring-reactive/blob/94b8835bb791cd7e8aa2573a50386d4f87ebccea/src/main/java/org/springframework/web/client/reactive/DefaultHttpRequestBuilder.java#L152). This is confusing since the method name is to create the request.

Perhaps the logic could be moved inside the factor or the method could be renamed?

**Comment by poutsma** [comment]
We have a very similar naming and usage pattern in the [non-reactive version of this interface](http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/http/client/ClientHttpRequestFactory.html): 

1. You create a request object via the factory
2. You populate said request object with headers and a body
3. You execute the request object, and get a response object
4. You read the headers and body from the response object

It has been a while since I wrote that code, but I think the main reason for the design was that it allows for streaming: some underlying libraries allow you to directly stream to the socket output, but you will have to give them URL and method upfront. It has served us well in other places too, as it allowed us to easily introduce client-side interception in 3.1, if I remember correctly.

Whether it's not intuitive is up for debate. I personally think that the Javadoc makes it quite clear how you are supposed to use the returned object: 

>The returned request can be written to, and then executed by calling `{@link ClientHttpRequest#execute()}`.

 But perhaps we can make a bit more clearer by making "written to" link to `setBody()`, or by adding some `@see` links.

Aside from changing the documentation, I would be against changing the method signature - especially for a non-fatal issue such as this - as this would separate the reactive from the non-reactive version. When spring-reactive is merged with Spring, the goal is to have one integral whole; not to introduce  separate reactive classes. Moreover, introducing reactive counterparts of existing classes can help our users in two ways: it gives them some familiarity while learning themselves reactive programming,  and it teaches them how they can change their own classes to be reactive.

**Comment by rstoyanchev** [comment]
This is related to https://github.com/spring-projects/spring-reactive/issues/96 so let's address for M1.

**Comment by bclozel** [comment]
Fixed by #96
