### ISSUE TITLE
Refactor request/response client contracts

### ISSUE THREAD

**Issue by bclozel** [spring-projects/spring-reactive#96]
There are a few issues with the current request/response client contracts - right now the `ReactiveHttpOutputMessage` and `ReactiveHttpInputMessage` work well for the server side, but not for the client counterpart.

First, the `ReactiveHttpOutputMessage` `Mono<Void> setBody(Flux<>)` method is misleading for the client side, since there's [no way to properly honor that contract](https://github.com/spring-projects/spring-reactive/blob/78ce096/src/main/java/org/springframework/http/client/reactive/ReactorClientHttpRequest.java#L92-L97): the request is never sent unless the `execute()` method is called on the request. Subscribing to the returned `Mono` won't work here.

Also, the `ReactiveHttpOutputMessage` `DataBufferAllocator allocator()` method can't be properly implemented here. Often the allocator is associated with the channel provided by the runtime; at the server level, getting a request/response pair means that the connection has been established and the underlying channel is available. On the client side, the channel is not created until we actively call `execute()`. Right now, the reactor WebClient is using a `DefaultDataBufferAllocator` (see [ReactorClientHttpRequest](https://github.com/spring-projects/spring-reactive/blob/78ce0966f904deccfa165870e57978bdea7324f0/src/main/java/org/springframework/http/client/reactive/ReactorClientHttpRequest.java#L60); that's why this issue hasn't been uncovered before.

The current client contracts also don't make a difference between the connection phase (connecting to the remote host+port pair) and the request phase (writing the body to the channel, getting the allocator); making such a difference could solve some of the issues we described previously. Also, this makes sense in a functional programming world where you want to use `retry` or `timeout` operators at different stages.

Also I've found some shortcomings to the current interceptors mechanism proposal (see #91). Because the RestTemplate interceptor mechanism dealt with `byte[]` to represent the body, the current proposal deals with `Flux<DataBuffer>`. But I see some value in proposing an extension mechanism where you could intercept the request both before and after the encoding of the body.

**Comment by rstoyanchev** [comment]
Indeed on the client side `setBody` cannot return a meaningful `Mono<Void>` because it is a simple setter and is not connected to the actual write. Moreover I believe the contract is in contradiction as it is currently written. For example you may decide to compose on the `Mono<Void>` to continue after the body is written but that cannot happen because you're also supposed to call `execute`.

**Comment by rstoyanchev** [comment]
As an example of what this could mean:
1. setBody and allocator() move down to `ServerHttpRequest`
2.  execute in `ClientHttpRequest` becomes connect
3.  connect returns a `Mono<ConnectedClientHttpRequest` with setBody and allocator

**Comment by poutsma** [comment]
I think we should be careful to keep acces to headers and body shared between client and server, so that the recently re-introduced `HttpMessageConverters` can continue to work. We don't want to go back to only having the lower-level `Encoder`/`Decoder` for that purpose; it results in duplicated code.

>As an example of what this could mean:
>1. setBody and allocator() move down to ServerHttpRequest
>2. execute in ClientHttpRequest becomes connect
>3. connect returns a Mono<ConnectedClientHttpRequest with setBody and allocator

I'm not in favor of introducing a separate  `ConnectedClientHttpRequest`; I would rather consider all `ClientHttpRequests` to be connected, so that any buffering necessary has to be done in code that uses the client-side API, not in the API itself.

My thought/hope is that we get pretty far in this direction by getting rid of the `execute` method in `ClientHttpRequest`, and changing the semantics of `ClientHttpRequestFactory` to return a `<ClientHttpRequest, ClientHttpResponse>` pair. Effectively, the `createRequest` becomes more like a connect method then. But I this is only off the top of my head, I haven't actually done this refactoring yet to see if it would actually work.

**Comment by smaldini** [comment]
FYI we use the following in reactor-netty  : 
```public final Mono<HttpInbound> get(String url,
			Function<? super HttpOutbound, ? extends Publisher<Void>> handler) {```

```java
HttpClient.create("localhost", httpServer.getListenAddress().getPort())
		                       .get("/test", (HttpOutbound c) -> 
                                                           c.addHeader("Authorization", auth)
				                             .upgradeToTextWebsocket())
		                       .flatMap(HttpInbound::receiveString)
		                       .log()
		                       .toList()
		                       .get()```
